export const ActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FORM_CART: "REMOVE_FORM_CART",
  UPDATE_CART: "UPDATE_CART",
  BUY_NOW: "BUY_NOW",
  CLEAR_CART: "CLEAR_CART",
  INITIAL_CART: "INITIAL_CART",
  SIGNIN: "SIGNIN",
  SIGNOUT: "SIGNOUT",
};
